services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: reservasi-booking-service

    ports:
      - "8000:80"

    volumes:
      - ./:/var/www/html

    depends_on:
      - mysql

    networks:
      - reservasi-network

  mysql:
    image: mysql:8.0

    container_name: reservasi-mysql

    restart: always

    environment:
      MYSQL_DATABASE: reservasi_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: reservasi_user
      MYSQL_PASSWORD: reservasi_pass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - reservasi-network

networks:
  reservasi-network:

volumes:
  mysql_data: